# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personalAssistant.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
# pyuic5 -x personalAssistant.ui -o personalAssistant.py
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PersonalAssistant_(object):
    def setupUi(self, PersonalAssistant_):
        PersonalAssistant_.setObjectName("PersonalAssistant_")
        PersonalAssistant_.resize(1123, 680)
        self.centralwidget = QtWidgets.QWidget(PersonalAssistant_)
        self.centralwidget.setObjectName("centralwidget")
        self.PersonalAssistant = QtWidgets.QLabel(self.centralwidget)
        self.PersonalAssistant.setGeometry(QtCore.QRect(0, 0, 1121, 681))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PersonalAssistant.setFont(font)
        self.PersonalAssistant.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.PersonalAssistant.setText("")
        self.PersonalAssistant.setPixmap(QtGui.QPixmap("C://GUI//gifs//icon.gif"))
        self.PersonalAssistant.setScaledContents(True)
        self.PersonalAssistant.setObjectName("PersonalAssistant")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(770, 620, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 72);\n"
"border-color: rgb(85, 255, 255);\n"
"\n"
"color: rgb(85, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 620, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 72);\n" "background-color: rgb(255, 0, 0);\n" "border-color: rgb(85, 255, 255);\n""\n" "color: rgb(85, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 501, 161))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C://GUI//gifs//loading.gif"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(674, 0, 441, 141))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C://GUI//gifs//ace-ace-v2.gif"))
        self.label_3.setObjectName("label_3")


        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 440, 421, 241))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C://GUI//gifs//frame.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 340, 291, 81))
        self.textBrowser.setStyleSheet("background:transparent;\n" "border-radius:none;\n" "color:white;\n" "font-size:60px;")
        self.textBrowser.setObjectName("textBrowser")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 250, 421, 241))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C://GUI//gifs//frame.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 520, 291, 81))
        self.textBrowser_2.setStyleSheet("background:transparent;\n" "border-radius:none;\n" "color:white;\n" "font-size:50px;")
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(845, 140, 271, 401))
        self.textBrowser_3.setStyleSheet("background:transparent;\n" "border-radius:none;\n" "color:white;\n" "font-size:50px;")
        self.textBrowser_3.setObjectName("textBrowser_3")

        PersonalAssistant_.setCentralWidget(self.centralwidget)

        self.retranslateUi(PersonalAssistant_)
        QtCore.QMetaObject.connectSlotsByName(PersonalAssistant_)

    def retranslateUi(self, PersonalAssistant_):
        _translate = QtCore.QCoreApplication.translate
        PersonalAssistant_.setWindowTitle(_translate("PersonalAssistant_", "Personal_Assistant"))
        self.pushButton.setText(_translate("PersonalAssistant_", "RUN"))
        self.pushButton_2.setText(_translate("PersonalAssistant_", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PersonalAssistant_ = QtWidgets.QMainWindow()
    ui = Ui_PersonalAssistant_()
    ui.setupUi(PersonalAssistant_)
    PersonalAssistant_.show()
    sys.exit(app.exec_())
